var Resources = {
   ShipSpriteSheet: new ex.Texture('./img/ship.png'),
   WitchSpriteSheet: new ex.Texture('./img/witch.png'),
   CircleShieldSheet: new ex.Texture('./img/circlesheildbig.png'),
   SquareShieldSheet: new ex.Texture('./img/squaresheildbig.png'),
   TriangleShieldSheet: new ex.Texture('./img/trianglesheildbig.png'),
   PlayerBullet: new ex.Texture('./img/WitchSpell.png'),
   CircleBadguySheet: new ex.Texture('./img/circlebadguyexplodes.png'),
   TriangleBadguySheet: new ex.Texture('./img/trianglebadguyexplodes.png'),
   SquareBadguySheet: new ex.Texture('./img/squarebadguyexplodes.png'),
   CircleBullet: new ex.Texture('./img/bullets/blueBullet.png'),
   SquareBullet: new ex.Texture('./img/bullets/greenBullet.png'),
   TriangleBullet: new ex.Texture('./img/bullets/yellowBullet.png'),
   CirclePortal: new ex.Texture('./img/blueportal.png'),
   CirclePortalClose: new ex.Texture('./img/blueportal2.png'),
   SquarePortal: new ex.Texture('./img/greenportal.png'),
   SquarePortalClose: new ex.Texture('./img/greenportal2.png'),
   TrianglePortal: new ex.Texture('./img/yellowportal.png'),
   TrianglePortalClose: new ex.Texture('./img/yellowportal2.png'),
   DiabloFontSheet: new ex.Texture("./fonts/DiabloFont.png"),
   Explode: new ex.Sound('./snd/explode1.wav', './snd/explode1.mp3'),
   Hit: new ex.Sound('./snd/explode2.wav', './snd/explode2.mp3'),
   BkgrdTrack: new ex.Sound('./snd/backingTrack.mp3', './snd/backingTrack.wav'),
   On: new ex.Sound('./snd/on.wav', './snd/on.mp3'),
   No: new ex.Sound('./snd/no.wav', './snd/no.mp3'),
   Nope: new ex.Sound('./snd/nope.wav', './snd/nope.mp3'),
   Absorb: new ex.Sound('./snd/absorb.wav', './snd/absorb.mp3'),
   PortalOpen: new ex.Sound('./snd/portalOpen.wav', './snd/portalOpen.mp3'),
   PortalClose: new ex.Sound('./snd/portalClose.wav', './snd/portalClose.mp3'),
   PlanetBg: new ex.Texture('./img/planet-bg.png'),
   FrontBg: new ex.Texture('./img/front-bg.png'),
   Torch: new ex.Texture('./img/torch.png'),
   Heart: new ex.Texture('./img/Heart.png'),
   Vignette: new ex.Texture('./img/vignette.png')
};