var Resources = {
   ShipSpriteSheet: new ex.Texture('./img/ship.png'),
   WitchSpriteSheet: new ex.Texture('./img/witch.png'),
   CircleShieldSheet: new ex.Texture('./img/circlesheildbig.png'),
   SquareShieldSheet: new ex.Texture('./img/squaresheildbig.png'),
   TriangleShieldSheet: new ex.Texture('./img/trianglesheildbig.png'),
   PlayerBullet: new ex.Texture('./img/WitchSpell.png'),
   CircleBadguySheet: new ex.Texture('./img/circlebadguyexplodes.png'),
   TriangleBadguySheet: new ex.Texture('./img/trianglebadguyexplodes.png'),
   SquareBadguySheet: new ex.Texture('./img/squarebadguyexplodes.png'),
   CircleBullet: new ex.Texture('./img/bullets/blueBullet.png'),
   SquareBullet: new ex.Texture('./img/bullets/greenBullet.png'),
   TriangleBullet: new ex.Texture('./img/bullets/yellowBullet.png'),
   DiabloFontSheet: new ex.Texture("./fonts/DiabloFont.png"),
   Explode: new ex.Sound('./snd/explode1.wav'),
   On: new ex.Sound('./snd/on.wav'),
   No: new ex.Sound('./snd/no.wav'),
   PlanetBg: new ex.Texture('./img/planet-bg.png'),
   FrontBg: new ex.Texture('./img/front-bg.png'),
   Torch: new ex.Texture('./img/torch.png')
};